version: '2'

services:

  wordpress:
    build: .
    depends_on:
      - mysql
    links:
      - mysql
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - wpnet
    volumes:
      - ./wp-content:/var/www/html/wp-content
    env_file: .env

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    networks:
      - wpnet
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8080:80
    networks:
      - wpnet
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: toor

networks:
  wpnet:

volumes:
  mysql-db: